export const CONTACT = {
  email: "aaliyan.kapadia@gmail.com",
  linkedin: "https://www.linkedin.com/in/aaliyank/",
  github: "https://github.com/AaliyanK",
  phone: "905-783-4673",
};

export const PROOF: string[] = [
  "Salesforce",
  "Electronic Arts",
  "Workday",
  "Asana",
  "Miro",
  "Glassdoor",
  "Reddit",
  "Braze",
  "Toast",
  "Udemy",
  "Chime",
  "Datadog",
];

export type Project = {
  key: string;
  title: string;
  tldr: string[];
  stack: string[];
  image: string | string[]; // can be a carousel
  link?: string; // optional link to project
  description?: string; // SEO description
  keywords?: string[]; // SEO keywords
};

export const PROJECTS: Project[] = [
  {
    key: "enterprise-ai",
    title: "Playfield: Enterprise Superintelligence App",
    tldr: [
      "Connects seamlessly with enterprise systems (e.g., Microsoft 365 via MCP server)",
      "Uses reasoning + tree algorithms to understand context and propose plans",
      "Enables employees to retrieve data, make changes, or spin up apps (e.g., live PDF viewer) in a secure sandbox",
      "Working with a banking design partner to build a secure prototype",
    ],
    stack: [
      "React",
      "TypeScript",
      "Python",
      "Node.js",
      "Flask",
      "SQLAlchemy",
      "MCP",
      "Enterprise AI",
      "Security",
      "Modal",
    ],
    image: [
      "/images/p1.png",
      "/images/p2.png",
      "/images/p3.png",
      "/images/p4.png",
      "/images/p5.png",
      "/images/p6.png",
      "/images/p7.png",
    ],
    link: "https://playfield-ashy.vercel.app/",
    description:
      "Enterprise-grade AI system that connects to internal tools, understands context, and empowers employees to securely query and modify data in real time. Built with React, TypeScript, Python, and MCP for seamless enterprise integration.",
    keywords: [
      "enterprise AI",
      "superintelligence",
      "MCP server",
      "enterprise automation",
      "AI assistant",
      "enterprise security",
      "React TypeScript",
      "Python Flask",
      "enterprise integration",
      "AI workflow automation",
    ],
  },
  {
    key: "communities",
    title: "Communities Platform With Slack Integration",
    tldr: [
      "More than 50K monthly active users",
      "Automated onboarding and questionnaires",
      "Slack sync and customizable welcome messages",
      "Drove $100K+ in renewals and upsells",
      "Event → invite linking with Slack & SparkPost email notifications",
      "Admin insights to measure community & event ROI",
    ],
    stack: [
      "React",
      "GraphQL",
      "TypeScript",
      "Python",
      "Flask",
      "SQLAlchemy",
      "Slack API",
      "Tailwind CSS",
    ],
    image: [
      "/images/comms1.png",
      "/images/comms3.png",
      "/images/comms4.png",
      "/images/comms5.png",
      "/images/comms6.png",
      "/images/comms7.png",
    ],
    description:
      "Scalable community platform with 50K+ monthly active users, featuring Slack integration, automated onboarding, and comprehensive analytics. Built with React, GraphQL, and Python Flask.",
    keywords: [
      "community platform",
      "Slack integration",
      "user onboarding",
      "GraphQL API",
      "React TypeScript",
      "Python Flask",
      "community management",
      "event management",
      "user analytics",
      "automation workflows",
    ],
  },
  {
    key: "insights",
    title: "Insights Dashboard with Queue Based Compute",
    tldr: [
      "Solved heavy metric computation with AWS SQS",
      "Faster reporting and support‑friendly views",
      "Unlocked $50K+ in upsells and renewals",
      "Won/expanded enterprise customers — e.g., Toast and EA",
      "Heatmaps, dynamic charts, and filters for actionable insight",
    ],
    stack: [
      "React",
      "GraphQL",
      "TypeScript",
      "Python",
      "Flask",
      "SQLAlchemy",
      "AWS SQS",
      "Tailwind CSS",
    ],
    image: [
      "/images/insights3.png",
      "/images/insights1.png",
      "/images/insights2.png",
      "/images/insights4.png",
      "/images/insights5.png",
    ],
    description:
      "Enterprise analytics dashboard with queue-based compute using AWS SQS, featuring heatmaps, dynamic charts, and real-time reporting. Delivered $50K+ in upsells for enterprise customers.",
    keywords: [
      "analytics dashboard",
      "AWS SQS",
      "queue based compute",
      "data visualization",
      "heatmaps",
      "enterprise reporting",
      "React GraphQL",
      "Python Flask",
      "real-time analytics",
      "business intelligence",
    ],
  },
  {
    key: "dtc-lighting",
    title: "DTC Home Goods Lighting Brand",
    tldr: [
      "3K–5K daily revenue; $120K+ sales passed in early months",
      "Full‑funnel engine across Meta, Google, TikTok Shop, YouTube, Affiliates, Amazon",
      "Luxury lighting catalogue with high‑converting funnel (email capture, social proof, affiliate endorsements)",
      "Scaled to $100K+ in 2 months (1.8× ROI, 1,756 orders, 2.1% CVR)",
      "Custom analytics: GA4, GTM, Klaviyo; server‑side event tracking",
    ],
    stack: [
      "Shopify",
      "GA4",
      "GTM",
      "Klaviyo",
      "Meta Ads",
      "Google Ads",
      "TikTok Shop",
      "Amazon",
    ],
    image: [
      "/images/nuve1.png",
      "/images/nuve2.png",
      "/images/nuve3.png",
      "/images/nuve4.png",
    ],
    description:
      "Scaled luxury lighting DTC brand to $100K+ revenue in 2 months with 1.8× ROI. Full-funnel marketing across Meta, Google, TikTok Shop, and Amazon with custom analytics.",
    keywords: [
      "DTC ecommerce",
      "luxury lighting",
      "Shopify store",
      "Meta ads",
      "Google ads",
      "TikTok shop",
      "Amazon marketplace",
      "conversion optimization",
      "GA4 analytics",
      "Klaviyo marketing",
    ],
  },
  {
    key: "furniture",
    title: "DTC Luxury Furniture Brand",
    tldr: [
      "Exclusive U.S. warehouse partnership",
      "Influencer + paid social playbook; Google & Meta core pipeline",
      "High‑converting Shopify funnel with CRO/A‑B tested landers per audience/creative",
      "Analytics & lifecycle: GA4, GTM, Klaviyo, server‑side tracking",
    ],
    stack: ["Shopify", "GA4", "GTM", "Klaviyo", "Meta Ads", "Google Ads"],
    image: [
      "/images/nord.png",
      "/images/nord2.png",
      "/images/nord3.png",
      "/images/nord4.png",
    ],
    description:
      "Luxury furniture DTC brand with exclusive warehouse partnership, influencer marketing, and high-converting Shopify funnel with A/B tested landing pages.",
    keywords: [
      "luxury furniture",
      "DTC brand",
      "Shopify ecommerce",
      "influencer marketing",
      "paid social",
      "Google ads",
      "Meta ads",
      "A/B testing",
      "conversion rate optimization",
      "warehouse partnership",
    ],
  },
  {
    key: "gaming",
    title: "Retro Gaming E‑commerce Brand (exited)",
    tldr: [
      ">$1M revenue in 8 months; 16K+ social followers",
      "Influencer partnerships & affiliates with celebrity creators",
      "High‑ROAS video ads (CPC ≈ $0.50, CTR > 2%); scaled Meta/Google spend profitably",
      "20K+ email list; $100K+ generated via lifecycle campaigns",
      "$184K on Google at profitable ROAS; Meta interest + broad targeting to scale globally",
    ],
    stack: [
      "Shopify",
      "GA4",
      "GTM",
      "Klaviyo",
      "Meta Ads",
      "Google Ads",
      "TikTok",
    ],
    image: [
      "/images/nost3.png",
      "/images/nost4.png",
      "/images/nost5.png",
      "/images/nost1.png",
      "/images/nost2.png",
    ],
    description:
      "Scaled retro gaming ecommerce brand to $1M+ revenue in 8 months with 16K+ social followers. High-ROAS video ads and influencer partnerships with celebrity creators.",
    keywords: [
      "retro gaming",
      "ecommerce brand",
      "Shopify store",
      "influencer partnerships",
      "video ads",
      "high ROAS",
      "Meta ads",
      "Google ads",
      "TikTok marketing",
      "email marketing",
    ],
  },
  {
    key: "youtube",
    title: "YouTube: AaliyanKapWrites",
    tldr: [
      "Monetized in 1 month; 1,000+ subs early",
      "500K lifetime views and $5K+ ad revenue",
      "Long‑form video essays; scripting, editing, and growth",
    ],
    stack: ["YouTube", "DaVinci Resolve", "Analytics", "Canva"],
    image: "/images/youtube1.png",
    description:
      "Monetized YouTube channel with 500K+ lifetime views and $5K+ ad revenue. Long-form video essays with scripting, editing, and audience growth strategies.",
    keywords: [
      "YouTube channel",
      "video content creation",
      "long-form videos",
      "video editing",
      "DaVinci Resolve",
      "content monetization",
      "audience growth",
      "video essays",
      "YouTube analytics",
      "content strategy",
    ],
  },
];
